import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Dekop Furniture Enterprise - меблі для вашого дому",
  description: "Generated by Vadym's Next.js Starter",
  metadataBase: new URL(process.env.NEXT_PUBLIC_VERCEL_URL ?? process.env.NEXT_PUBLIC_URL ?? "http://localhost"),
  openGraph: {
    images: "/og-image.png", // Path to your image you placed in the public folder
  },

  icons: {
    icon: [
      { url: "/favicon.png", sizes: "16x16", type: "image/png" },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
