// app/layout.tsx
import type { Metadata } from "next";
import Script from "next/script"; // Import Next.js Script component
import QueryProvider from "@/app/providers/QueryProvider";
import ClientLayout from "./ClientLayout";
import "./global.css";
import { CartProvider } from "./context/CartContext";
import { FavoritesProvider } from "./context/FavoritesContext";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/next";

// Font optimization with Ukrainian (Cyrillic) support
// Note: next/font/google disabled in build due to network restrictions
// Using CSS @import with font-display: swap instead (see global.css)
// TODO: Re-enable when deploying to Vercel (will work in production)
// import { Inter } from 'next/font/google';
// const inter = Inter({
//   subsets: ['latin', 'cyrillic'],
//   display: 'swap',
//   variable: '--font-inter',
//   preload: true,
//   weight: ['400', '500', '600', '700'],
//   fallback: ['Arial', 'Helvetica', 'sans-serif'],
// });

export const metadata: Metadata = {
  title: "Dekop Furniture Enterprise - меблі для вашого дому",
  description: "Generated by Vadym's Next.js Starter",
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000"),
  openGraph: {
    title: "Dekop Furniture Enterprise",
    description: "Меблі для вашого дому",
    url: process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
    images: [`${process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000"}/og-image.png`],
    type: "website",
  },
  icons: {
    icon: [
      { url: "/favicon.png", sizes: "16x16", type: "image/png" },
    ],
  },
};

// --- GTM Configuration ---
const GTM_ID = "GTM-TVVGC6PQ"; 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <Script id="google-tag-manager-head" strategy="beforeInteractive">
        {`
          (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','${GTM_ID}');
        `}
      </Script>
      
      <body>
        <noscript>
          <iframe 
            src={`https://www.googletagmanager.com/ns.html?id=${GTM_ID}`}
            height="0" 
            width="0" 
            style={{ display: "none", visibility: "hidden" }}
          />
        </noscript>

        <QueryProvider>
          <CartProvider>
            <FavoritesProvider>
              <ClientLayout>{children}</ClientLayout>
              <SpeedInsights />
              <Analytics />
            </FavoritesProvider>
          </CartProvider>
        </QueryProvider>
      </body>
    </html>
  );
}