import React, { useState } from "react";
import Header from "@/app/components/header/header";
import Footer from "@/app/components/footer/footer";
import Head from "next/head";
import { useRouter } from "next/router";
import "@/app/globals.css";
import styles from "./layout.module.css"; 

export default function PagesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();
  const [menuOpen, setMenuOpen] = useState(false);

  const getPageName = () => {
    const pathSegments = router.asPath
      .split("?")[0]
      .split("/")
      .filter((segment) => segment !== "");

    const lastSegment = pathSegments[pathSegments.length - 1] || "Home";
    return formatName(lastSegment);
  };

  const formatName = (str: string) => {
    return str
      .replace(/-/g, " ")
      .replace(/(^\w|\s\w)/g, (m) => m.toUpperCase());
  };

  const handleMenuToggle = () => {
    setMenuOpen((prev) => !prev);
  };

  return (
    <>
      <Head>
        <title>
          {`${getPageName()} | Dekop Furniture Enterprise - меблі для вашого дому`}
        </title>
        <meta name="description" content="Generated by Vadym's Next.js Starter" />
        <link rel="icon" href="/favicon.png" sizes="16x16" type="image/png" />
      </Head>

      {/* Overlay that shows when the menu is open */}
      {menuOpen && (
        <div
          className={styles.overlay}
          onClick={() => setMenuOpen(false)} // Close menu on overlay click
        ></div>
      )}
      <Header menuOpen={menuOpen} onMenuToggle={handleMenuToggle} />
      <main>{children}</main>
      <Footer />
    </>
  );
}
